export const Users = [
  {
    id:1,
    profilePicture: "pictures/srk.jpg",
    username: "Adnan Rahim Khan",
  },
  {
    id:2,
    profilePicture: "pictures/srk.jpg",
    username: "Akheel",
  },
  {
    id:3,
    profilePicture: "pictures/srk.jpg",
    username: "Alex",
  },
  {
    id:4,
    profilePicture: "pictures/srk.jpg",
    username: "Dora ",
  },
  {
    id:5,
    profilePicture: "pictures/srk.jpg",
    username: "Thomas shelby",
  },
  {
    id:6,
    profilePicture: "pictures/srk.jpg",
    username: "Eleven",
  },
  {
    id:7,
    profilePicture: "pictures/srk.jpg",
    username: "Travis Scott",
  },
  {
    id:8,
    profilePicture: "pictures/srk.jpg",
    username: "Kristen Stewart",
  },
  {
    id:9,
    profilePicture: "pictures/srk.jpg",
    username: "robert downey",
  },
  {
    id:10,
    profilePicture: "pictures/srk.jpg",
    username: "Selmon Bhoi",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "pictures/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "pictures/srk.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "pictures/1.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "pictures/srk.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "pictures/1.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "pictures/srk.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "pictures/1.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "pictures/srk.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "pictures/1.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "pictures/srk.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];